name: Build Docker Image (H100 Pythia)

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  pull_request:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for H100
        run: |
          docker build -t pythia-h100-test .