name: Push Local Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  push-only:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull from GitHub Actions cache (skip if local-only)
        run: echo "Push already done locally."